@host=http://localhost:3000

GET {{host}}/favorites 

###
POST {{host}}/favorites
Content-Type: application/json

{
    "name":"A New Hope",
    "type":"movie",
    "url":"http://swapi.dev/api/films/1/"
}