version: '3.8'
services:
  ## App Containers ##
  # nginx
  server:
    # many of these configurations weren't choices, they were found in the official documentation for the nginx image
    image: 'nginx:stable-bullseye'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
      # delegated - data written by the container isn't instantly reflected in the host machine delivering in "batches". used to optimize performace
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  ## Utility Containers ##
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # artisan:
  # npm:

# volumes:


