version: '3.8'
services:
  ## App Containers ##
  # nginx
  server:
    # many of these configurations weren't choices, they were found in the official documentation for the nginx image
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
      # delegated - data written by the container isn't instantly reflected in the host machine delivering in "batches". used to optimize performace
  # mysql:
  # ## Utility Containers ##
  # composer:
  # artisan:
  # npm:

volumes:


